### ISSUE TITLE
It seems that the simulation does not started automatically?

### ISSUE THREAD

**Issue by yuffff** [lyraymond53/CS184-ClothSim#1]

**Comment by lyraymond53** [comment]
Oh right, I didn't link it to the class spec, but you have to press "P" in the GUI to start the simulation. There's some other commands in the spec as well for camera and timestep controls. That said, my implementation is imperfect and starts to artifact the further into the spec you go

https://cs184.eecs.berkeley.edu/sp19/article/34/assignment-4-cloth-simulation
